### ISSUE TITLE
NullPointerException while disabling plugin

### ISSUE THREAD

**Issue by PapiCapi** [Dablakbandit/Bank#20]
Hello, i'm using the 4.0.5 version with Paper 249 and when the plugin is disabling, sometimes this error is spammed :

`[14:25:03] [Server thread/WARN]: java.lang.NullPointerException
[14:25:03] [Server thread/WARN]: 	at me.dablakbandit.bank.save.SQLBaseLoader.save(SQLBaseLoader.java:337)
[14:25:03] [Server thread/WARN]: 	at me.dablakbandit.bank.save.SaveType.save(SaveType.java:23)
[14:25:03] [Server thread/WARN]: 	at me.dablakbandit.bank.save.LoaderThread$SaveRunner.run(LoaderThread.java:51)
[14:25:03] [Server thread/WARN]: 	at me.dablakbandit.bank.save.LoaderRunnable.runRunners(LoaderRunnable.java:80)
[14:25:03] [Server thread/WARN]: 	at me.dablakbandit.bank.save.LoaderThread.stop(LoaderThread.java:124)
[14:25:03] [Server thread/WARN]: 	at me.dablakbandit.bank.BankCoreHandler.onDisable(BankCoreHandler.java:262)
[14:25:03] [Server thread/WARN]: 	at me.dablakbandit.bank.BankPlugin.onDisable(BankPlugin.java:37)
[14:25:03] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[14:25:03] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399)
[14:25:03] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516)
[14:25:03] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502)
[14:25:03] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495)
[14:25:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:405)
[14:25:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:741)
[14:25:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:752)
[14:25:03] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:992)
[14:25:03] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)`

This is really a big problem because without a SIGKILL, it doesn't stop and the server can't reboot or just stop

**Comment by Dablakbandit** [comment]
These will no longer happen in beta builds
