### ISSUE TITLE
deposit money bug

### ISSUE THREAD

**Issue by kimven** [Dablakbandit/Bank#23]
[13:26:37] [Server thread/WARN]: java.lang.NullPointerException
[13:26:37] [Server thread/WARN]:        at me.dablakbandit.core.utils.anvil.AnvilUtil.open(AnvilUtil.java:135)
[13:26:37] [Server thread/WARN]:        at me.dablakbandit.bank.inventory.AnvilInventory.open(AnvilInventory.java:60)
[13:26:37] [Server thread/WARN]:        at me.dablakbandit.core.players.CorePlayers.setOpenInventory(CorePlayers.java:88)
[13:26:37] [Server thread/WARN]:        at me.dablakbandit.bank.inventory.money.BankMoneyInventory.deposit(BankMoneyInventory.java:85)
[13:26:37] [Server thread/WARN]:        at me.dablakbandit.bank.inventory.BankInventoryHandler.lambda$consumeSound$31(BankInventoryHandler.java:114)
[13:26:37] [Server thread/WARN]:        at me.dablakbandit.bank.inventory.BankInventoryHandler.lambda$null$26(BankInventoryHandler.java:84)
[13:26:37] [Server thread/WARN]:        at me.dablakbandit.core.inventory.InventoryHandler.parseClick(InventoryHandler.java:157)
[13:26:37] [Server thread/WARN]:        at me.dablakbandit.core.players.CorePlayerManager.onInventoryClick(CorePlayerManager.java:234)
[13:26:37] [Server thread/WARN]:        at catserver.server.executor.asm.generated.GeneratedEventExecutor15.execute(Unknown Source)
[13:26:37] [Server thread/WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67)
[13:26:37] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:26:37] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503)
[13:26:37] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488)
[13:26:37] [Server thread/WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2114)
[13:26:37] [Server thread/WARN]:        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38)
[13:26:37] [Server thread/WARN]:        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12)
[13:26:37] [Server thread/WARN]:        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[13:26:37] [Server thread/WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[13:26:37] [Server thread/WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[13:26:37] [Server thread/WARN]:        at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[13:26:37] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:839)
[13:26:37] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472)
[13:26:37] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:776)
[13:26:37] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630)
[13:26:37] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by kimven** [comment]
[00:51:13] [Server thread/INFO]: zxm1021 issued server command: /bank open
[00:51:13] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'bank open' in me.dablakbandit.core.commands.AbstractCommand$PluginReflectCommand(bank)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[SimpleCommandMap.class:git-CatServer-1.12.2-74a3a50]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[CraftServer.class:git-CatServer-1.12.2-74a3a50]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1596) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1439) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_251]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:834) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:771) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:625) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at me.dablakbandit.bank.command.base.BankEndArgument.checkPermissionInfo(BankEndArgument.java:61) ~[?:?]
        at me.dablakbandit.bank.command.base.BankEndArgument.hasPermission(BankEndArgument.java:56) ~[?:?]
        at me.dablakbandit.bank.command.arguments.OpenArgument.hasPermission(OpenArgument.java:36) ~[?:?]
        at me.dablakbandit.core.commands.EndArgument.onCommand(EndArgument.java:25) ~[?:?]
        at me.dablakbandit.core.commands.AdvancedCommand.onCommand(AdvancedCommand.java:119) ~[?:?]
        at me.dablakbandit.core.commands.AbstractCommand$ReflectCommand.execute(AbstractCommand.java:212) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[SimpleCommandMap.class:git-CatServer-1.12.2-74a3a50]
        ... 14 more

**Comment by kimven** [comment]
@Dablakbandit

**Comment by Dablakbandit** [comment]
@kimven Ensure no other plugins cause errors when a player joins the server
